FROM rasa/rasa-sdk:3.0.1

# The Rasa SDK image runs as non-root user by default. Hence, you have to switch
# back to the `root` user if you want to install additional dependencies

USER root
COPY ./actions/ /app/actions

RUN pip3 install beautifulsoup4==4.9.3
RUN pip3 install python-decouple==3.3
RUN pip3 install fuzzywuzzy
# Switch back to a non-root user
USER 1001