FROM 0420202019/rasa-kinyarwanda-dev:latest
#FROM $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/rasa_kinyarwanda_image:latest

WORKDIR /app

COPY ./*.yml /app/
COPY ./data /app/data/
COPY ./tests /app/tests/
COPY ./models /app/models/

VOLUME /app
VOLUME /app/data
VOLUME /app/models

WORKDIR /app
CMD ["run","-m","/app/models","--credentials","/app/credentials.yml","--endpoints","/app/endpoints.yml","--enable-api","--cors","*","--debug"]