FROM nginx:1.19

COPY ./nginx-config-files/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx-config-files/ssl.conf.template /etc/nginx/templates/ssl.conf.template
COPY ./nginx-config-files/rasax.nginx.template /etc/nginx/templates/rasax.nginx.template
EXPOSE 8080