FROM rasa/rasa-x:1.0.1

#COPY ./models /app/models
COPY ./environments.yml /app/environments.yml
COPY ./credentials.yml /app/credentials.yml
COPY ./endpoints.yml /app/endpoints.yml
#COPY ./logs /logs
#COPY ./auth /app/auth