version: "3.4"

x-database-credentials: &database-credentials
  DB_HOST: "postgres.dev.mbaza.digital"
  DB_PORT: "5432"
  DB_USER: "mbaza"
  DB_PASSWORD: "mbaza"
  DB_LOGIN_DB: "rasa"

x-rabbitmq-credentials: &rabbitmq-credentials
  RABBITMQ_HOST: "rabbitmq.dev.mbaza.digital"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "Q22Ryf431kx"

x-redis-credentials: &redis-credentials
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "THZDbkY86,2Nyyh"
  REDIS_DB: "1"
  REDIS_CACHE_DB: "2"
  ACCEPTABLE_QUERY_COUNT_NUMBER: "50000"

x-duckling-credentials: &duckling-credentials
  RASA_DUCKLING_HTTP_URL: "http://duckling:8000"

x-nginx-host-variables: &nginx-host-variables
  RASA_X_HOST: "rasa_x:5002"
  RASA_USER_APP: "rasa_x_actions:5055"
  RASA_PRODUCTION_HOST: "rasa-production:5005"

x-rasax-credentials: &rasax-credentials
  RASA_X_HOST: "http://rasa_x:5002"
  RASA_X_USERNAME: "admin"
  RASA_X_PASSWORD: "mbazarasa"
  RASA_X_TOKEN: "Nt9kyfWpSR1E4MZ"
  JWT_SECRET: "T8D0ZsCDR5FCSwQbIKUYqqaQt"
  RASA_USER_APP: "http://rasa_x_actions:5055"
  RASA_PRODUCTION_HOST: "http://rasa-production:5005"
  RASA_WORKER_HOST: "http://rasa-worker:5005"
  RASA_TOKEN: "T2CSnZqlOlh5X6c"

x-rasa-credentials: &rasa-credentials
  <<: *rabbitmq-credentials
  <<: *rasax-credentials
  <<: *database-credentials
  <<: *redis-credentials
  <<: *duckling-credentials
  RASA_TOKEN: "T2CSnZqlOlh5X6c"
  RASA_MODEL_PULL_INTERVAL: 10
  RABBITMQ_QUEUE: "rasa_production_events"
  RASA_TELEMETRY_ENABLED: "true"


x-rasa-services: &default-rasa-service
  restart: always
  image: "rasa/rasa:2.7.0-full"
  volumes:
      - config:/.config
  #expose:
  #  - "5005"
  command: >
    x
    --no-prompt
    --production
    --config-endpoint http://rasa_x:5002/api/config?token=Nt9kyfWpSR1E4MZ
    --port 5005
    --jwt-method HS256
    --jwt-secret T8D0ZsCDR5FCSwQbIKUYqqaQt
    --auth-token 'T2CSnZqlOlh5X6c'
    --cors "*"
    --debug
  depends_on:
    - rasa_x
    - redis

services:
  rasa_x:
    restart: always
    image: "git.risa.gov.rw:5050/risa/risa-gcino-projects/risa-innovation-division-projects/mbaza-chatbot/mbaza-chatbot-rasa-implementation/mbaza-chatbot-rasa-language-model-english/development/rasa_x:latest"
    # build:
    #    context: .
    #    dockerfile: Dockerfile.rasa_x
    # expose:
    #   - "5002"
    ports:
      - "5002:5002"
    volumes:
      #- models:/app/models
      #- environments.yml:/app/environments.yml
      #- credentials.yml:/app/credentials.yml
      #- endpoints.yml:/app/endpoints.yml
      - logs:/logs
      - auth:/app/auth
    environment:
      <<: *database-credentials
      <<: *rasa-credentials
      SELF_PORT: "5002"
      DB_DATABASE: "rasa"
      RASA_MODEL_DIR: "/app/models"
      PASSWORD_SALT: "wuKhm4auWFfJEC,"
      RABBITMQ_QUEUE: "rasa_production_events"
      RASA_X_USER_ANALYTICS: "0"
      SANIC_RESPONSE_TIMEOUT: "3600"
      RUN_DATABASE_MIGRATION_AS_SEPARATE_SERVICE: "true"
    # depends_on:
    #   - db
    networks:
      - infrastructure_default

  db-migration:
    entrypoint: ["python"]
    command: ["-m", "rasax.community.services.db_migration_service"]
    restart: always
    image: "rasa/rasa-x:0.40.0"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || kill 1"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 2s
    #expose:
    #  - "8000"
    environment:
      <<: *database-credentials
      RUN_DATABASE_MIGRATION_AS_SEPARATE_SERVICE: "true"
      MPLCONFIGDIR: "/tmp/.matplotlib"
    # depends_on:
    #   - db
    networks:
     - infrastructure_default

  rasa-production:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "production"
      DB_DATABASE: "tracker"
      MPLCONFIGDIR: "/tmp/.matplotlib"
      RASA_MODEL_SERVER: "http://rasa_x:5002/api/projects/default/models/tags/production"
    networks:
     - infrastructure_default

  rasa-worker:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "worker"
      DB_DATABASE: "worker_tracker"
      MPLCONFIGDIR: "/tmp/.matplotlib"
      RASA_MODEL_SERVER: "http://rasa_x:5002/api/projects/default/models/tags/production"
    networks:
     - infrastructure_default
    #  - internal_infrastructure

  rasa_x_actions:
    restart: always
    image: "git.risa.gov.rw:5050/risa/risa-gcino-projects/risa-innovation-division-projects/mbaza-chatbot/mbaza-chatbot-rasa-implementation/mbaza-chatbot-rasa-language-model-english/development/rasa_x_actions:latest"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.actions
    #expose:
    #  - "5055"
    depends_on:
      - rasa-production
    networks:
     - infrastructure_default
    #  - internal_infrastructure

  # db:
  #   restart: always
  #   image: "bitnami/postgresql:11.9.0"
  #   expose:
  #     - "5432"
  #   environment:
  #     POSTGRESQL_USERNAME: "${DB_USER:-admin}"
  #     POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
  #     POSTGRESQL_DATABASE: "${DB_DATABASE:-rasa}"
  #   volumes:
  #     - db:/bitnami/postgresql
  #   networks:
  #    - internal_infrastructure

  # rabbit:
  #   restart: always
  #   image: "bitnami/rabbitmq:${RABBITMQ_VERSION}"
  #   environment:
  #     RABBITMQ_HOST: "rabbit"
  #     RABBITMQ_USERNAME: "user"
  #     RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  #     RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
  #   expose:
  #     - "5672"
    # networks:
    #  - internal_infrastructure

  duckling:
    restart: always
    image: "rasa/duckling:0.1.6.5-r0"
    #expose:
    #  - "8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]
    networks:
     - infrastructure_default

  rasa_x_nginx:
    restart: always
    image: "git.risa.gov.rw:5050/risa/risa-gcino-projects/risa-innovation-division-projects/mbaza-chatbot/mbaza-chatbot-rasa-implementation/mbaza-chatbot-rasa-language-model-english/development/rasa_x_nginx:latest"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
  #  expose: 
  #    - "80"
    ports:
      - "8080:8080"
    #   - "8443:8443"
    # volumes:
      # - certs:/etc/certs
     # - /etc/rasa/nginx-config-files/nginx.conf:/etc/nginx/nginx.conf
     # - /etc/rasa/nginx-config-files/ssl.conf.template:/etc/nginx/templates/ssl.conf.template
     # - /etc/rasa/nginx-config-files/rasax.nginx.template:/etc/nginx/templates/rasax.nginx.template
    environment:
      <<: *nginx-host-variables
    depends_on:
      - rasa_x
      - rasa-production
      - rasa_x_actions
    networks:
      - infrastructure_default

  redis:
    restart: always
    image: "bitnami/redis:6.2.1"
    environment:
      REDIS_PASSWORD: "THZDbkY86,2Nyyh"
    #expose:
    #  - "6379"
    networks:
      - infrastructure_default

networks:
 infrastructure_default:
  driver: overlay
  driver_opts:
   encrypted: "true"

volumes:
  config:
    driver: local
  # db:
  #   driver: local
  logs:
    driver: local
  auth:
    driver: local
  # certs:
  #   driver: local
